import fs from "fs";
import path from "path";
import { registry } from "../src/registry";

async function build() {
  const targetDir = path.join(process.cwd(), "public/r");
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const componentsIndex: string[] = [];

  for (const [key, item] of Object.entries(registry)) {
    const registryEntry = {
      ...item,
      files: item.files.map((file) => {
        if (typeof file === "string") {
          return {
            path: file,
            content: fs.readFileSync(path.join(process.cwd(), file), "utf8"),
            type: "registry:ui"
          };
        }
        return {
          path: file.path,
          type: file.type,
          target: file.target,
          content: fs.readFileSync(path.join(process.cwd(), file.path), "utf8"),
        };
      }),
    };

    fs.writeFileSync(
      path.join(targetDir, `${key}.json`),
      JSON.stringify(registryEntry, null, 2)
    );

    // Convert keys like "my-button" to "MyButton" to safely grab named exports
    const componentName = key.split('-').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');

    if (item.type === "registry:example") {
      componentsIndex.push(`  "${key}": dynamic(() => import("@/registry/example/${key}").then((m: any) => ({ default: m.default || m.${componentName} })) as any),`);
    } else if (item.type === "registry:ui") {
        const file = item.files[0];
        const filePath = typeof file === "string" ? file : file.path;
        const importPath = filePath.replace("src/", "@/").replace(/\.tsx?$/, "");
        componentsIndex.push(`  "${key}": dynamic(() => import("${importPath}").then((m: any) => ({ default: m.default || m.${componentName} })) as any),`);
    }
}

  // Generate components index for documentation
  const componentsIndexFile = `// This file is auto-generated by scripts/build-registry.ts
import dynamic from "next/dynamic";
import * as React from "react";

export const registryComponents: Record<string, React.ComponentType<any>> = {
${componentsIndex.join("\n")}
};
`;

  fs.writeFileSync(
    path.join(process.cwd(), "src/registry/components.ts"),
    componentsIndexFile
  );

  console.log("✅ Registry files generated successfully!");
}

build().catch(console.error);
