import fs from "fs";
import path from "path";
import { registry } from "../src/registry";

async function build() {
  const targetDir = path.join(process.cwd(), "public/r");
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const componentsIndex: string[] = [];

  for (const [key, item] of Object.entries(registry)) {
    const registryEntry = {
      ...item,
      files: item.files.map((file) => ({
        path: file,
        content: fs.readFileSync(path.join(process.cwd(), file), "utf8"),
        type: "registry:ui"
      })),
    };

    fs.writeFileSync(
      path.join(targetDir, `${key}.json`),
      JSON.stringify(registryEntry, null, 2)
    );

    if (item.type === "registry:example") {
      componentsIndex.push(`  "${key}": dynamic(() => import("@/registry/example/${key}")),`);
    }
  }

  // Generate components index for documentation
  const componentsIndexFile = `// This file is auto-generated by scripts/build-registry.ts
import dynamic from "next/dynamic";
import * as React from "react";

export const registryComponents: Record<string, React.ComponentType<any>> = {
${componentsIndex.join("\n")}
};
`;

  fs.writeFileSync(
    path.join(process.cwd(), "src/registry/components.ts"),
    componentsIndexFile
  );

  console.log("✅ Registry files generated successfully!");
}

build().catch(console.error);
